import { motion } from 'framer-motion';

export default function About() {
  return (
    <motion.div 
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -10 }}
      className="max-w-3xl mx-auto w-full px-4 py-12 prose prose-indigo"
    >
      <h1 className="text-3xl font-bold text-[#064e3b] mb-6">About TruthScan AI</h1>
      <p className="text-lg text-gray-600 mb-8">
        TruthScan AI was built to empower consumers. In a world where food labels are intentionally complex and marketing claims border on deceptive, we believe everyone has the right to know exactly what they are putting into their bodies.
      </p>

      <h2 className="text-xl font-bold text-[#064e3b] mt-8 mb-4">How it works</h2>
      <p className="mb-4 text-gray-700">
        When you capture an image of a product, our application utilizes advanced AI vision models to read the label text and identify the product. The AI cross-references the visible ingredients with wide-ranging databases and knowledge bases to provide comprehensive, plain-language insights.
      </p>

      <h2 className="text-xl font-bold text-[#064e3b] mt-8 mb-4">Technology Stack</h2>
      <ul className="space-y-2 mb-8 text-gray-700 list-disc pl-5">
        <li><strong>Frontend:</strong> React, Tailwind CSS, shadcn/ui, framer-motion</li>
        <li><strong>AI Engine:</strong> Google Gemini 3.1 Pro via `@google/genai`</li>
        <li><strong>State & Storage:</strong> Zustand (Secure 7-day Local Storage persistence) & Firebase Firestore Sync</li>
      </ul>

      <div className="bg-[#f0fdf4] p-6 rounded-2xl border border-[#16a34a]/20 mt-12 shadow-[0_8px_30px_rgb(0,0,0,0.04)]">
        <h3 className="font-bold text-[#064e3b] mb-2">Disclaimer</h3>
        <p className="text-sm text-gray-600">
          The safety scores and ingredient categorizations provided by TruthScan AI are generated by large language models based on available public guidelines. They do not constitute certified medical, dietary, or legal advice. Always review packaging physically and consult with health professionals when making dietary choices.
        </p>
      </div>
    </motion.div>
  );
}
